/* eslint-disable @typescript-eslint/naming-convention */

export const expectedOverlay = {
  1: {
    value: 'linear-gradient(180deg, #000000 5%, rgba(18,18,20,0.36) 50%, #000000 100%)',
    type: 'color',
  },
  2: {
    value: 'linear-gradient(180deg, #000000 5%, rgba(18,18,20,0.20) 50%, #000000 100%)',
    type: 'color',
  },
  dimmed: { value: 'rgba(18,18,20,0.36)', type: 'color' },
  transparent: { value: 'rgba(18,18,20,0.20)', type: 'color' },
};

export const expectedBackground = {
  buttonPrimary: {
    hover: { value: '#88CC57', type: 'color', description: '#88CC57' },
    default: { value: '#99E662', type: 'color', description: '#99E662' },
    disabled: { value: '#39363B', type: 'color', description: '#39363B' },
  },
  alert: { value: '#E92026', type: 'color', description: '#E92026' },
  sarchBar: { value: '#000000', type: 'color', description: '#000000' },
  dropdown: { value: '#000000', type: 'color', description: '#000000' },
  cardHeader: { value: '#000000', type: 'color', description: '#000000' },
  active: {},
  activeHover: { value: '#ffffffcc', type: 'color', description: '#FFFFFF' },
  main: {},
  foreground: { value: '#282629', type: 'color', description: '282629' },
  input: {},
  light: { value: '#39363B', type: 'color', description: '#39363B' },
  verylight: { value: '#514C53', type: 'color' },
  buttonSecondary: {
    hover: { value: '#1A1A33', type: 'color', description: '1A1A33' },
    default: { value: '#31306B', type: 'color', description: '31306B' },
    disabled: { value: '#39363B', type: 'color', description: '#39363B' },
  },
  notification: {
    info: { value: '#31306B', type: 'color', description: '31306B' },
  },
  buttonTetiary: {
    hover: { value: '#1E1C1F', type: 'color', description: '#1E1C1F' },
  },
};

export const expectedBorder = {
  light: { value: '#39363B', type: 'color', description: '#39363B' },
  'very-light': { value: '#282629', type: 'color', description: '282629' },
  default: { value: '#807984', type: 'color', description: '#807984' },
  primary: { value: '#99E662', type: 'color', description: '#99E662' },
  alert: { value: '#E92026', type: 'color', description: '#E92026' },
  white: { value: '#f7f7f7', type: 'color', description: '#FFFFFF' },
  'white-transparent': {
    value: '#ffffff4d',
    type: 'color',
    description: '#FFFFFF',
  },
  rainbow: {},
};

export const expectedText = {
  white: { value: '#f7f7f7', type: 'color', description: '#FFFFFF' },
  link: { value: '#f7f7f7', type: 'color', description: '#FFFFFF' },
  linkHover: { value: '#A69DAB', type: 'color' },
  redlinkHover: { value: '#D62328', type: 'color', description: 'D62328' },
  subtext: { value: '#A69DAB', type: 'color' },
  dark: { value: '#121112', type: 'color', description: '#121112' },
  disabled: { value: '#514C53', type: 'color' },
  backLink: { value: '#807984', type: 'color', description: '#807984' },
  placeholder: { value: '#807984', type: 'color', description: '#807984' },
  alert: { value: '#E92026', type: 'color', description: '#E92026' },
  highlight: { value: '#99E662', type: 'color', description: '#99E662' },
  dimmed: { value: '#514C53', type: 'color' },
};

export const expectedTypography = {
  '32 semibold': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '44', type: 'lineHeights' },
    fontSize: { value: '32', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '24 semibold': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '36', type: 'lineHeights' },
    fontSize: { value: '24', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '24 regular': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '400',
    lineHeights: { value: '36', type: 'lineHeights' },
    fontSize: { value: '24', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '20 regular': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '400',
    lineHeights: { value: '28', type: 'lineHeights' },
    fontSize: { value: '20', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '20 semibold': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '28', type: 'lineHeights' },
    fontSize: { value: '20', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '16 semibold': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '26', type: 'lineHeights' },
    fontSize: { value: '16', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '16 regular': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '400',
    lineHeights: { value: '26', type: 'lineHeights' },
    fontSize: { value: '16', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '14 semibold': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '20', type: 'lineHeights' },
    fontSize: { value: '14', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '14 regular': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '400',
    lineHeights: { value: '20', type: 'lineHeights' },
    fontSize: { value: '14', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '12 semibold': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '18', type: 'lineHeights' },
    fontSize: { value: '12', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '12 regular': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '400',
    lineHeights: { value: '18', type: 'lineHeights' },
    fontSize: { value: '12', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
  '10 semi': {
    fontFamilies: { value: 'Satoshi', type: 'fontFamilies' },
    fontWeight: '500',
    lineHeights: { value: '14', type: 'lineHeights' },
    fontSize: { value: '10', type: 'fontSizes' },
    letterSpacing: { value: '0%', type: 'letterSpacing' },
    paragraphSpacing: { value: '0', type: 'paragraphSpacing' },
    textCase: { value: 'none', type: 'textCase' },
    textDecoration: { value: 'none', type: 'textDecoration' },
  },
};
