const exampleTopBar = {
  signInButtonLabel: 'Sign In',
  signOutButtonLabel: 'Sign Out',
  signUpButtonLabel: 'Create an Account',
  workerSignupLabel: 'Worker Signup',
  companySignupLabel: 'Company Signup',
};

const exampleSidebar = {
  jobsLabel: 'Jobs',
  settingsLabel: 'Settings',
  profileLabel: 'Profile',
  helpAndSupportLabel: 'Help & Support',
  copyrightLabel: 'GigBridge. All Rights Reserved.',
};

const PasswordError = {
  title: 'Your password should contain at least:',
  passwordRequiredError: 'Password is required',
  passwordWhitespaceError: 'Whitespace is not allowed',
  passwordMinError: 'min 8 character',
  passwordConfirmRequiredError: "Password don't match",
  passwordFormatError: 'Password format is invalid',
  validationMinCharLabel: '8 characters',
  validationCapitalLetterLabel: '1 upper case letter',
  validationSpecialCharLabel: '1 special character',
};

const SignUp = {
  title: 'Sign up',
  emailLabel: 'E-mail:',
  emailPlaceholder: 'Enter your E-mail address',
  emailError: 'You must enter e-mail address',
  passwordLabel: 'Password:',
  passwordPlaceholder: 'Enter your password',
  passwordConfirmLabel: 'Confirm Password:',
  passwordConfirmPlaceholder: 'Confirm your password',
  checkboxLabel: 'Accept',
  checkboxLink: 'Terms of Use',
  checkboxLabel2: 'and',
  checkboxLink2: 'Privacy Policy',
  termsBackButtonLabel: 'Back',
  termsTitle: 'Terms and Conditions',
  termsError: 'You must accept Terms and Conditions',
  submitButtonLabel: 'Create Account',
  loginText: 'Already have an account?',
  loginLink: 'Login',
  exploreFeed: 'Explore Feed',
  successTitle: 'E-mail Sent',
  successMessage: 'We have sent you a link to confirm your email. Please check your spam folder if it doesn\'t arrive.',
  verificationLinkExpiryMessage: 'The verification link will expire in ',
  verificationLinkExpiryTime: '24 hours.',
  linkExpired: 'Link Expired',
  linkExpiredMessage: 'The verification link you clicked on has expired. Tap the button below to get a new one.',
  resendVerificationLink: 'Resend verification link',
  expiredMessage: 'Verification token expired, please resend the email!',
};

const SignIn = {
  title: 'Sign in',
  emailLabel: 'Login:',
  emailPlaceholder: 'Please enter your email',
  emailError: 'You must enter e-mail address',
  passwordLabel: 'Password:',
  passwordPlaceholder: 'Please enter your password',
  submitButtonLabel: 'Login',
  signUpText: 'Don\'t have a talent account?',
  signUpLink: 'Signup',
  resetPass: 'Reset Password',
};

const image = {
  fileSpecification: 'File specification',
};
const fileSpecificationModal = {
  title: 'File Specification',
  images: 'Images',
  imagesExtension: 'File type: .PNG or .JPEG',
  imagesSize: 'Max file size: 20MB',
  imagesDimension: 'Aspect ratio: Aspect ratio: We recommend using a 16:9 aspect ratio (e.g. 1920x1080 pixels)',
  videos: 'Videos',
  videosExtension: 'File type: .MP4 or .MOV',
  videosSize: 'Max file size: 256MB',
  videosLength: 'Max length: 5 minutes',
  videosEncoding: 'Encoding: H.264',
  videosDimension: 'Aspect ratio: We recommend using a 16:9 aspect ratio (e.g. 1920x1080 pixels)',
};

const ResetPassword = {
  title: 'Choose a new password',
  passwordLabel: 'Password:',
  passwordPlaceholder: 'Enter your password',
  passwordConfirmLabel: 'Repeat Password:',
  passwordConfirmPlaceholder: 'Enter your password again',
  submitButtonLabel: 'Reset Password',
};

const RecoverPassword = {
  title: 'Recover Password',
  emailLabel: 'E-mail:',
  emailPlaceholder: 'E-mail address',
  emailError: 'Provide e-mail address',
  submitButtonLabel: 'Recover Password',
  successTitle: 'Instruction Sent',
  successMessage: 'We have sent you a link to reset your password. Please check your spam folder if it doesn\'t arrive.',
  cancelText: 'Cancel',
  loginLink: 'Login',
};

const onBoarding = {
  name: {
    firstNameLabel: 'First name*',
    lastNameLabel: 'Last name*',
    firstNamePlaceholder: 'Please enter your first name',
    lastNamePlaceholder: 'Please enter your last name',
    title: 'Create your profile',
    subtitle: 'The Draft is all about the profile cards. Build your first one.',
    firstNameError: 'you must enter your first name',
    lastNameError: 'you must enter your last name',
    descriptionError: 'description is required',
    spaceError: 'field should not contain spaces',
    genericErrorSaveName: 'Error in saving name',
    limitError: 'field should not contain more than 100 characters',
    captionError: 'field should not contain more than 2000 characters',
    minLimitError: 'field should contain at least 2 characters',
    specialCharErr: 'field should not contain special characters',
    numberCharErr: 'field should not contain numbers.',
  },
  image: {
    desktopTitle: 'Add details to your card',
    desktopSubtitle:
      'The Draft is all about the profile cards. Build your first one.',
    title: 'Add photo',
    subtitle: 'Upload an image that will be a cover for your profile',
    imageInputLabel: 'Drag and drop file or',
    imageInputBrowse: 'Browse',
    imageInputInfo: 'Max file size: 2 mb, format: png, jpg, At least 290x500px',
    imageLabel: 'Image:',
    imageError: 'Selected file is too big or unsupported format',
    uploadingText: 'Uploading File...',
    loading: 'Uploading File...',
    upload: {
      select: 'Select image or video to upload',
      dropFile: 'Or drag and drop a file',
      fileInfo: ['PNG, JPEG, MP4 or MOV', 'Less than 20MB for image and 256MB for videos', 'Up to 5 minutes for videos'],
      aspectRatio: 'Aspect ratio: We recommend using fully vertical videos (9:16) or 1080x1920 pixel size. Other suitable options include: 2:3 or 4:5.',
    },
  },
  mantra: {
    title: 'Add Mantra',
    subtitle: 'Add mantra to your image',
    mantraPlaceholder: 'Write something',
    mantraLabel: 'Mantra:',
  },
  bio: {
    desktopTitle: 'Add card with bio',
    desktopSubtitle:
      'The Draft is all about the profile cards. Build your first one.',
    title: 'Add bio',
    subtitle: 'Build second card by adding bio to your profile. ',
    bioLabel: 'Bio:',
    bioPlaceholder: 'Add a short bio to your profile',
    bioDisclaimer:
      'This information will be added to your extended profile. You can edit this informations later. Bio is needed to make your profile public',
    bioPreviewTitle: 'Bio Preview',
    bioPreviewSubtitle: 'Bio Preview',
  },
  success: {
    successTitle: 'Looking good!',
    successSubtitle:
      'Your basic deck is done. You can explore your feed now all go to your profile and continue on creating cards.',
    primaryButton: 'Explore Feed',
    secondaryButton: 'Edit Profile',
  },
  skipModal: {
    skipModalTitle: 'Are you sure?',
    skipModalSubtitleBio:
      'Without a bio, your profile will not be publicly visible',
    skipModalSubtitleProject:
      'Without projects, your profile will not be publicly visible',
    skipModalSkip: 'Yes, skip this step',
    skipModalCancelBio: 'No, add bio',
    skipModalCancelProject: 'No, add project',
  },
  project: {
    title: 'Add first project',
    subtitle: 'Projects are important part of the Draft.',
    disclaimer:
      'Projects will be added to your extended profile. You can add more projects details later. Project is needed to make your profile public',
    titleLabel: 'Project Title / Company',
    titlePlaceholder: 'Project, company, study',
    titleError: 'You must enter project title',
    roleLabel: 'Role',
    rolePlaceholder: 'Project role if relevant',
    tagsLabels: 'Tags',
    tagsPlaceholder: 'Relevant Skills',
    startLabel: 'Start Date',
    startPlaceholder: 'Start Date',
    startError: 'You must enter start date',
    endLabel: 'End Date',
    endPlaceholder: 'End Date',
    endError: 'You must enter end date or select ongoing',
    checkLabel: 'Ongoing',
    projectPreviewTitle: 'Project Preview',
    projectPreviewSubtitle: 'Project Preview',
  },
  previewCard: {
    title: 'Card Preview',
    subtitle: 'This is your first card preview',
  },
};
const profile = {
  deleteLabel: 'Delete',
  editLabel: 'Edit',
  addBio: 'Add Bio',
  cancel: 'Cancel',
  save: 'Save',
  next: 'Next',
  back: 'Back',
  addSkills: "Can't find your skill or technology above?",
  brand: 'Brand',
  content: 'Content',
  resume: 'Resume',
  filterSkills: 'Filter Skills',
  filter: 'Filter',
  followersLabel: 'Followers',
  followingLabel: 'Following',
  addBlock: 'Block',
  addCard: 'Card',
  showProjects: 'SHOW PROJECTS',
  hideProjects: 'HIDE PROJECTS',
  noProfileBlock: {
    message: 'Your profile is currently hidden from the feed. Start getting noticed by adding a cover card and an introduction.',
    noCards: {
      title: 'Create your brand stack',
      line1: 'Introduce who you are to the world using a collection of cards',
      line2: 'Your cards will be used to represent you on the feed to hiring companies and other users so make your first impression count!',
      addCard: `+ ${'\xa0'}Add Card`,
    },
    noBlocks: {
      title: 'Craft your introduction',
      discription: 'Let’s add a text block to introduce who you are to anyone who views your profile.',
      addBlock: `+ ${'\xa0'}Add Text Block`,
    },
  },
  block: {
    project: {
      title: 'Project Block',
      desc: 'Showcase achievements that demonstrate your expertise',
    },
    workExperience: {
      title: 'Experience Block',
      successAddMessage: 'Added Experience Successfully',
      successEditMessage: 'Edited Experience Successfully',
      form: {
        steps: {
          summary: 'Summary', description: 'Description',
        },
        role: {
          subtitle: 'Add basics about the role',
          placeholder: 'Ex. Senior Product Manager',
          label: 'Role title',
        },
        functionalRole: {
          placeholder: 'Search for your role',
          label: 'Functional role',
        },
        organisationName: {
          placeholder: 'Organisation name',
          label: 'Organisation name',
        },
        location: {
          placeholder: 'Type the main location you worked from',
          label: 'Location',
        },
        employmentType: {
          placeholder: 'Please select',
          label: 'Employment type',
        },
        locationType: {
          placeholder: 'Please select',
          label: 'Location type',
          labelBlock: 'Location Type',
        },
        roleType: {
          placeholder: 'Please select',
          label: 'Role type',
          peopleManager: 'People manager',
        },
        totalPeopleManaged: {
          placeholder: 'How many people did you directly manage?',
          label: 'Total people managed',
        },
        date: {
          startDate: 'Start date',
          endDate: 'End date',
          ongoing: 'Ongoing project',
          now: 'Now',
        },
        skillsAndTechnologiesUsed: {
          placeholder: 'Add any soft skills, technical skills and technologies that you used on this project. We recommend adding at least your top 5.',
          label: 'Skills and technologies',
          inputPlaceholder: 'Type new skill or technology here',
          error: "You've reached the 20 skills maximum that can be added to this experience.",
          subtitle: 'Let us match you better by adding more information about that experience',
        },
        benefits: {
          placeholder: 'Select any perks and benefits that were part of this role.',
          label: 'Benefits (optional)',
        },
        description: {
          placeholder: 'Describe your role to help hiring managers understand your experience within the context of this organisation. Focus on your key achievements that highlight how you applied any skills or used any technologies to get results.',
          label: 'Description (optional)',
          subtitle: 'Write your description here',
        },
        roleDescription: {
          placeholder: 'Describe your role by adding at least 3 key points, if possible. Focus on your key achievements and help hiring managers understand your experience within the context of this organisation.',
          label: 'Role description (optional)',
        },
      },
    },
    highlight: {
      title: 'Highlight Block',
      desc: 'Emphasise something that is important with an image or video',
      form: {
        title: {
          label: 'Title (optional)',
          placeholder: 'Add a brief caption to your image or video',
        },
      },
    },
    text: {
      title: 'Text Block',
      desc: 'Add a note to share information about who you are',
      form: {
        title: {
          label: 'Title (optional)',
          placeholder: 'What is this block about?',
        },
        description: {
          label: 'Description',
          placeholder: 'Add text',
        },
      },
    },
    delete: {
      messageTitle: 'Are you sure?',
      description: 'Are you sure you want to remove this block from your profile?',
      submitButton: 'Yes, remove',
      cancelButton: ' No, keep the block',
      deleteExperience: {
        title: 'Delete Experience',
        description1: 'Are you sure you want to delete your',
        description2: 'experience? All projects associated with this experience will also be deleted.',
        cancelButton: 'Cancel',
        submitButton: 'Yes, delete',
      },
      deleteProject: {
        title: 'Delete Project',
        description1: 'Are you sure you want to delete',
        description2: '?',
        cancelButton: 'Cancel',
        submitButton: 'Yes, delete',
      },
      deleteEducation: {
        title: 'Delete Education',
        description1: 'Are you sure you want to delete your',
        description2: 'education?',
        cancelButton: 'Cancel',
        submitButton: 'Yes, delete',
      },
    },
  },
  title: 'Profile',
  editName: {
    description: 'Edit your name and location',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    locationLabel: 'Location',
    firstNamePlaceholder: "What's your first name?",
    lastNamePlaceholder: "What's your last name?",
    locationPlaceholder: 'Where are you currently based?',
    locationError: 'Location is required',
  },
  education: {
    title: 'Education',
    modalTitle: 'Education Block',
    updateMessage: 'Updated education successfully',
    addMessage: 'Added education successfully',
    formSteps: {
      step1: 'Summary',
      step2: 'Description',
    },
    addEducationCTA: 'Add education',
    addEducationText: 'Add your highest level of formal education and any relevant professional qualifications',
    fields: {
      institutionName: {
        label: 'Institution name',
        placeholder: 'Institution name',
      },
      educationType: {
        label: 'Education type',
        placeholder: 'Undergraduate Degree',
      },
      fieldOfStudy: {
        label: 'Field of Study',
        placeholder: 'Economics',
      },
      startDate: {
        label: 'Start date',
        placeholder: 'Start date',
      },
      endDate: {
        label: 'End date',
        placeholder: 'End date',
        now: 'Now',
      },
      onGoing: {
        label: 'Ongoing',
        placeHolder: 'Ongoing',
      },
      grade: {
        label: 'Grade (optional)',
        labelBlock: 'Grade',
        placeholder: '2.1',
      },
      skills: {
        label: 'Skills and technologies',
        description: 'Add any soft skills, technical skills and technologies that you used while completing this education. We recommend adding at least your top 5.',
        placeholder: 'Type new skill or technology here',
        errorMessage: "You've reached the 20 skills maximum that can be added to this education.",
      },
      description: {
        label: 'Description (optional) ',
        placeholder: 'Type your description here',
      },
    },
  },
  link: {
    addLinkForm: {
      ModalHeading: 'Add link',
      modalTitle: 'Add a link',
      subTitle: 'Share an important link that you want to stand out.',
      description: 'Add link description', // TODO: update link description
      successMessage: 'Added link block successfully',
      linkTitle: {
        linkTitleLabel: 'Link title',
        linkTitlePlaceholder: 'My link',
      },
      url: {
        label: 'URL',
        placeholder: 'www.yourlink.com',
      },
    },
    editLinkForm: {
      editLinkTitle: 'Edit link',
      editLinkSubTitle: 'Share an important link that you want to stand out.',
      description: 'Add link description', // TODO: update link description
      successMessage: 'Added link block successfully',
      editTitle: {
        editLinkTitleLabel: 'Title',
        editLinkTitlePlaceholder: 'Title',
      },
      editLinkDescription: {
        editLinkDescriptionLabel: 'Description (optional)',
        editLinkDescriptionPlaceholder: 'Explain what your link is about',
      },
      editBtnText: {
        editBtnTextLabel: 'Button',
        editBtnTextPlaceholder: 'More',
      },
      editUrl: {
        editUrlLabel: 'URL',
        editUrlPlaceholder: 'www.yourlink.com',
      },
      imageInputLabel: 'Add link preview',
      linkImageSizeError: 'Image should be less than 20 MB',
      fileExtension: 'PNG or JPEG',
      fileSize: 'Less than 20MB',
      moreBtnLabel: 'Discover',
    },
  },
};
const errorMessages = {
  notFound:
    "Sorry we couldn't find a page you are looking for. Make sure the address is correct",
  imagePath: 'Must be a valid file path or a File object',
  errorInFetchingUrl: 'Error extracting website name:',

};
const bio = {
  title: 'Bio',
  editBid: 'EDIT BIO',
  readMore: 'Read More',
  noBio: 'Add  bio to your profile',
  addBio: 'Add Bio',
  addbio: 'Add bio',
  showLess: 'Show Less',
  edit: 'EDIT',
  editName: 'Edit Name',
  firstNameLabel: 'First name*',
  lastNameLabel: 'Last name*',
  firstNamePlaceholder: 'Please enter your first name',
  lastNamePlaceholder: 'Please enter your last name',
  addImage: 'Add image',
  editCard: 'Edit Card',
  placeHolderText: 'Placeholder Text',
  imageInputLabel: 'Drag and drop file or',
  imageInputBrowse: 'Browse',
  imageInputInfo: 'Max file size: YY mb, format: png, jpg At least 290x500px',
  editImageText: 'Edit your image now and text in next step',
  editMantraText: 'Edit text on your card',
  editPreviewText: 'Your card preview',
};
const projects = {
  steps: { summary: 'Summary', description: 'Description' },
  sideProject: {
    add: {
      description: "Add side projects, interesting things you've done and showcase achievements that demonstrate your skills",
      subtitle: 'Add side projects',
    },
  },
  title: 'Experience',
  addProject: 'Project Block',
  noProjects: 'Add projects to your profile',
  addProjectButton: 'Add projects',
  titlePlaceholder: 'Add a title to this block',
  titleLabel: 'Title',
  skills: 'Skills',
  skillsPlaceholder: 'Add tags that best describe the key skills needed for this project',
  description:
    "Add to your profile anything you are proud of. Company role it's just a tip of an iceberg. Draft projects are containers for anything you do.",
  ongoingProjects: 'Ongoing Project',
  startDate: 'Start date',
  now: 'Now',
  endDate: 'End date',
  createdSuccess: 'Project added succesfully',
  createdError: 'Error in adding project',
  newProject: 'NEW PROJECT',
  updatedSuccess: 'Project updated succesfully',
  updatingError: 'Error in updating project',
  details: 'Details',
  uploadLimit: 'You can upload up to 2 images',
  fileUploadLimitError: 'You have reached the file limit',
  more: 'More',
  timeline: 'Experience Timeline',
  editTimeline: 'EDIT TIMELINE',
  less: 'less',
  thumbnail: 'Thumbnail',
  descriptionPlaceholder: 'Add text description of what the project was about.',
  descriptionLabel: 'Description (optional)',
  addMediaLabel: 'Add media (optional)',
  fileSpecification: 'File specification',
  deleteMessage: 'Project deleted successfully',
  resume: {
    workExperience: 'Work experience',
    sideProjects: 'Side projects',
    add: {
      description: 'Add where you have worked and describe each work experience',
      subtitle: 'Add work experience',
    },
    deleteSuccess: 'Experience deleted successfully.',
    deleteEducationSuccess: 'Education deleted successfully.',
  },
  form: {
    projectName: {
      subTitle: 'Add basics about the project',
      label: 'Project name',
      placeholder: 'Type a project name',
    },
    role: {
      label: 'Role (optional)',
      placeholder: 'Highlight your role on this project',
    },
    associatedWith: {
      subTitle: 'This project will appear under this experience on your profile.',
      label: 'Associate with experience (optional)',
      placeholder: 'Select the relevant experience to link this project',
    },
    skillsAndTechnologiesUsed: {
      subTitle: 'Add basics about the project',
      suggestionLabel: 'Suggested skills based on project association with ',
      label: 'Skills and technologies',
      placeholder: 'Add any soft skills, technical skills and technologies that you used on this project. Choose from the list of suggestions below that are taken from the associated experience.',
      inputPlaceholder: 'Type new skill or technology here',
      infoDescription: 'Any new skills added to this project will also be added to the associated experience.',
      warningDescription: "You've reached the 20 skills maximum available for this project.",
      warningDescriptionForAssociated: "You've reached the 20 skills maximum that can be added to this project. Select from the current skills above or edit the associated experience.",
    },
    skillsAndTechnologiesUsedUnassociated: {
      placeholder: 'Add any soft skills, technical skills and technologies that you used on this project. We recommend adding at least your top 5.',
    },
    description: {
      label: 'Description (optional)',
      placeholder: 'Describe how you applied any skills or used any technologies on this project',
      subtitle: 'It is important to let hiring managers know the significance of the project and your impact',
    },
  },
};

const buttonText = {
  next: 'Next',
  submit: 'Submit',
  skip: 'Skip',
  back: 'Back',
  cancel: 'Cancel',
  save: 'Save',
  edit: 'EDIT',
  close: 'Close',
  preview: 'Preview',
  start: 'Start',
  done: 'Done',
  create: 'Create',
  skipThisStep: 'Skip this step',
  selectAll: 'Select All',
  clear: 'Clear',
  selected: 'Selected',
  discard: 'Discard',
  post: 'Post',
  share: 'Share',
  more: 'More',
};

const navBarText = {
  feed: 'Explore',
  workspace: 'Workspace',
  community: 'Community',
  searchPlaceholder: 'Search The Draft...',
  profile: {
    myProfile: 'My Profile',
    settings: 'Settings',
    preferences: 'Preferences',
    reportBug: 'Report a bug',
    suggestIdea: 'Suggest an idea',
    help: 'Help',
    createCompanyProfile: 'Create Company Profile',
    createOrganization: 'Create Organization',
    switchAccounts: 'Switch Accounts',
    logout: 'Logout',
  },
  create: 'Create',
};

const company = {
  createCompanyPage: 'Create Company Page',
  createCompanySubTitle: 'Create a company profile or claim existing one.',
  companyUrl: 'Company URL',
  companyEmail: 'Company Email',
  name: 'Name*',
  logo: 'Logo',
  headcount: 'Headcount*',
  industries: 'Industries*',
  summary: 'Summary (optional)',
  companyUrlPlaceholder: 'URL',
  emailPlaceholder: 'Your work email',
  namePlaceholder: 'Enter company Name',
  headcountPlaceholder: 'Choose employee range',
  industriesPlaceholder: 'Add tags that describe your industry',
  summaryPlaceholder: 'Add summary',
  logoPlaceholder: '300x300px recommended, format: png, jpg',
  logoError: 'Company logo must be 200px by 200px (or greater with the same aspect ratio)',
  checking: 'Checking',
  isThisYourCompany: 'Is this your company?',
  existProfile: 'This profile already exists.',
  companyEditText: 'If you want to edit this company profile you need to request access.',
  button: {
    viewProfile: 'View the profile',
    notMyCompany: 'It’s not my company',
  },
  draftURLErr: 'This URL already exists. Edit your organization name above.',
  companyUrlError: 'Please enter company URL',
  validUrlError: 'Please enter valid URL',
  completeProfileError: {
    name: 'Please enter company name',
    headcount: 'Please choose head count',
    industry: 'Please select at least one industry',
  },
  step: {
    url: 'Company URL',
    validateEmail: 'Validate email',
    completeProfile: 'Complete profile',
    createCards: 'Create Cards',
  },
  submittingProfile: {
    header: 'Submit company for review',
    body: 'Confirm the company URL and your valid business email to continue.',
  },
  basicInformation: {
    header: 'Basic Informations',
    body: 'Complete form with basic informations about company',
  },
  profile: {
    navbarHeader: {
      brand: 'Brand',
      insights: 'Insights',
      timeline: 'Timeline',
      content: 'Content',
      jobs: 'Jobs',
      people: 'People',
    },
  },
  companyNotFound: 'Company not found!',
  userNameAvailable: 'This username is available!',
  contentNotFound: 'No content',
  contentNotFoundMessage: 'Not content to display',
  noJobs: 'No Jobs',
  noJobsMessage: 'No jobs added',
};
const orgInsightsTab = {
  dataFetching: 'Data fetching...',
  comingSoon: 'Comeback in 15 mins.',
  summary: 'Summary',
  orgType: 'Org Type',
  companyType: 'Company Type',
  headcount: 'Headcount',
  yearFounded: 'Year Founded',
  website: 'Website',
  hq: 'HQ',
  expertise: 'Expertise',
  principalBusinessActivity: 'Principal Business Activity',
  competitors: 'Competitors',
  investors: 'Investors',
  funding: 'Funding',
  fundingRoundClosed: 'Funding rounds closed',
};

const organization = {
  draftUrlPath: 'thedraft.io/org/',
  create: {
    splashScreen: {
      title: 'Who can create and verify an organization?',
      content: 'Only leaders at an organization or those part of a people function will be granted Admin access and can verify the profile. If this doesn’t fit your job description or role, please have a colleague who is responsible for this create the organization.',
    },
    step: {
      website: 'Website',
      orgDetails: 'Org details',
      confirmEmail: 'Confirm email',
      setUsername: 'Set Username',
      brand: 'Brand',
    },
    title: 'Create organization',
    websiteDetails: 'Look up your organization',
    organizationDetails: 'Organization details',
    websiteDetailsSubtitleOne: 'Your organization may have a profile on The Draft already. Confirm your website domain to check.',
    websiteDetailsSubtitleTwo: 'If there is an existing profile, verify the organization to claim your profile.',
    organizationDetailsSubtitleOne:
      'Confirm the name and type of organization.',
    organizationDetailsSubtitleTwo:
      'Your profile URL will align with the organisation name so that it is not misleading or ambiguous.',
    orgDetailForm: {
      organizationName: {
        label: 'Organization name',
        placeholder: 'Organization name',
      },
      orgDraftURL: {
        label: 'The Draft URL',
        placeholder: 'organization-name',
        error: 'This URL already exists. Edit your organization name above.',
      },
      orgType: {
        label: 'Org type',
        placeholder: 'Select type',
      },
      companyType: {
        label: 'Company Type',
        placeholder: 'Select Type',
      },
      websiteURL: {
        label: 'Website',
        placeholder: 'www.example.com',
      },
      organizationURL: {
        label: 'Organization URL',
        placeholder: 'Enter Organization URL',
      },
    },
    confirmEmail: {
      title: 'Confirm email',
      subTitle: 'Verify that you work at this organization.',
      otpSubTitle: 'Enter the confirmation code sent to ',
      workEmail: {
        label: 'Work email',
        placeholder: 'Your work email',
        domainNameError: "Doesn't match your entered domain ",
      },
      verificationSentMsg: 'A verification code was sent to ',
      code: 'Code',
      acceptedEmails: 'Accepted emails: ',
      confirmEmailMessage: 'I confirm that I am authorized to act on behalf of this organization to create and manage this profile.',
      resendCode: 'Resend code',
    },
    foundMessageTitle: 'We found your organization',
    foundMessageSubTitle: 'We already have an organization using the same domain',
    viewTheProfile: 'View the profile',
  },
};

const meltwater = {
  labels: {
    status: 'Status:',
    contentType: 'Source:',
    fetchDate: 'Fetch date:',
  },
  newsFeed: 'Meltwater Newsfeed',
  filters: {
    socialBlogs: { label: 'Blogs', value: 'social_blogs' },
    news: { label: 'News', value: 'news' },
    pinterest: { label: 'Pinterest', value: 'pinterest' },
  },
  settings: {
    feedSettings: 'Feed Settings',
    feedSettingsSubtext: 'Input your XML or RSS link from your Meltwater feed below.',
    xml: {
      label: 'XML',
      placeholder: 'Enter XML Url',
    },
    rss: {
      label: 'RSS',
      placeholder: 'Enter RSS Url',
    },
  },
};

const workspace = {
  menu: {
    savedCards: 'Saved',
    createdCards: 'Content',
    jobs: 'Jobs',
    myApplications: 'Applications',
    cronycleFeeds: {
      title: 'Cronycle Feeds',
      manageFeeds: 'Manage Feeds',
    },
    meltwater: 'Meltwater',
    settings: 'Settings',
    createdPosts: 'Posts',
    createdLinks: 'Links',
    preferences: 'Preferences',
  },
  applicationFilters: {
    dateOpened: 'Date Opened',
    functionalRole: 'Functional Role',
    locationType: 'Location Type',
    dateApplied: 'Date Applied',
    employmentType: 'Employment Type',
    salaryFrom: 'Salary From',
    salaryTo: 'Salary To',
  },
  jobFilters: {
    dateOpened: 'Date Opened',
    functionalRole: 'Functional Role',
    locationType: 'Location Type',
    employmentType: 'Employment Type',
    salaryFrom: 'Salary From',
    salaryTo: 'Salary To',
  },
  jobStatus: {
    open: 'Open',
    pending: 'Pending',
    close: 'Closed',
  },
  settings: {
    feedSettings: 'Feed Settings',
    atsIntegration: 'ATS Integration',
    greenHouse: 'Greenhouse',
    greenHouseIntro: 'When new jobs are posted on Greenhouse they will automatically be added to The Draft for you to review before appearing on the explore page.',
    getStarted: 'Get Started',
    apiIntro: 'We will walk you through the steps to complete your integration in a few minutes. You will need to login to your Greenhouse account and follow the instructions outlined.',
    createHarvestAPIKey: 'Create Harvest API Key',
    createWebHook: 'Create Webhook',
    harvestStepOneLink: 'https://app.greenhouse.io/configure/dev_center/credentials',
    harvestStepOne: 'Open \'API Credentials\' in Greenhouse (you may need to sign in first)',
    harvestStepTwo1: '2. Click the ',
    harvestStepTwo2: '\'Create New API Key\'',
    harvestStepTwo3: ' button on Greenhouse.',
    harvestStepThree: '3. Enter following fields in the pop-up.',
    apiType: 'API Type',
    harvest: 'Harvest',
    partner: 'Partner',
    unlistedVendor: 'Unlisted Vendor',
    description: 'Description',
    theDraft: 'The Draft',
    harvestStepFour1: '4. Click the ',
    harvestStepFour2: '\'Manage Permissions\'',
    harvestStepFour3: ' button and copy the API Key created by Greenhouse.',
    harvestStepFive: '5. Paste the API key below.',
    pasteKey: 'Paste your API key here',
    harvestStepSix: '6. Click the \'I have stored the API Key\' button.',
    harvestStepSeven1: '7. Click the checkboxes for ',
    harvestStepSeven2: '\'Jobs\', \'Job Posts\', \'Job Stages\'',
    harvestStepSeven3: ' and ',
    harvestStepSeven4: '\'Sources\'.',
    harvestStepEight1: '8. Click the',
    harvestStepEight2: ' \'Save\' ',
    harvestStepEight3: 'button on Greenhouse to confirm.',
    continueStep: 'Continue',
    webhookStepOne: 'Open Greenhouse webhook form',
    webhookStepTwo: '2. Copy the following fields into Greenhouse',
    webhookStepOneLink: 'https://app8.greenhouse.io/web_hooks',
    webhookName: 'Name this web hook',
    draftWebhook: 'The Draft Webhook: Job post updated',
    when: 'When',
    jobPostCreated: 'Job post created',
    jobPostUpdated: 'Job post updated',
    endPointURL: 'Endpoint URL',
    secretKey: 'Secret key',
    webhookStepThree1: '3. Click',
    webhookStepThree2: ' \'Create Web hook\' ',
    webhookStepThree3: 'button on Greenhouse to confirm.',
    done: 'Done',
    wrongKey: 'The API key didn\'t work. Make sure you have selected the correct permissions for this on Greenhouse.',
    harvestSuccess: 'Greenhouse Harvest API successfully integrated.',
    greenhouseResetIntro: 'Your Greenhouse account is now connected. New jobs posted on Greenhouse will automatically be added to The Draft for you to review before appearing on the explore page.',
    reset: 'Reset API keys',
    connected: 'Connected',
    apiKeyRequired: 'API Key is required',
    webhookConfirmationError: "We didn't get a signal for this webhook. Check you've entered the fields correctly and have saved the webhook on Greenhouse.",
  },
  applicants: 'APPLICANTS',
  filterTitle: 'Filter',
  status: 'Status',
  opened: 'Opened',
  noJob: 'No jobs added',
  viewJob: 'View Job',
  skills: 'SKILLS',
  applied: 'APPLIED',
  addFirstJob: 'Your jobs will be listed here',
  addJob: 'Create Job',
  jobDetails: 'JOB DETAILS',
  draftCompanyUrl: 'thedraft.io',
  draftCompanyUsername: 'the-draft',
};
const jobs = {
  addRequirements: 'Add requirement',
  addRequirementsPlaceholder: 'You are experienced in building and implementing large-scale systems across various projects',
  usd: 'USD',
  minRange: '$40,000',
  maxRange: '$70,000',
  noJob: {
    noApplication: 'No applications',
    noApplicationMessage: 'Your applications will appear here so you can refer back to them later.',
  },
  deleteJob: 'Delete Job',
  deleteSubText: 'Are you sure you want to delete this Job? All data, applicants and messages will be lost.',
  addJobStep1Title: 'Add job overview',
  addJobStep1Subtitle: 'The Draft is all about the  cards. Build your first card for the job.',
  roleLabel: 'Role',
  rolePlaceholder: 'Enter role',
  locationLabel: 'Location',
  locationTypeLabel: 'Location type',
  jobTypeLabel: 'Job type',
  jobTypePlaceholder: 'Select Job type',
  salaryFromLabel: 'Salary from',
  salaryFromPlaceholder: 'Salary from',
  salaryToLabel: 'Salary to',
  salaryToPlaceholder: 'Salary to',
  salaryRangeInvalid: 'Minimum should be less than the maximum',
  atLeastOneRequirement: 'The job should have at least one written requirement',
  oteFromRequiredField: 'OTE from is a required field',
  imageLabel: 'Background',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'Add Description',
  descriptionDisclamer: 'Descriptions will only be visible in the detailed job view',
  edit: 'EDIT',
  publish: 'Publish',
  openJob: 'Open job',
  closeJob: 'Close job',
  loadMore: 'Load More',
  showLess: 'Show Less',
  reviewYourJob: 'Review your job',
  reviewJobDecs: 'Your basic deck is done. You can explore your feed now all go to your profile and continue on creating cards',
  backToEdit: 'Back to edit',
  createJobPost: 'Create Job Post',
  saveJobPost: 'Save Job Post',
  addSnaphotTitle: 'Add job snapshot card',
  addSnapshotSubtitle: 'The Draft is all about the cards. Create additional card to summarise the job with any supporting information that is important.',
  addSnapshotLabel: 'Add snapshot',
  image: {
    imageInputInfo: 'Max file size: 1 mb, format: png, jpg',
    error: 'File size should be less than 1 MB',
  },
  card: {
    preview: 'See your card preview',
    create: 'Create job cards',
  },
  error: {
    salary: 'salaryTo must be greater than salaryFrom',
  },
  addJobModal: {
    connectWithATS: 'Connect with ATS',
    connectWithATSSubtitle: 'Choose how you want to add job description',
    addJobManually: 'Add job manually',
    lever: 'LEVER',
  },
  list: {
    role: 'Role',
    id: 'ID',
    dateCreated: 'Date created',
    location: 'Location',
    type: 'Type',
    salary: 'Salary',
    status: 'Status',
    applicants: 'Applicants',
  },
  moreMenu: {
    edit: 'Edit',
    viewJobDetails: 'View job details',
    unpublish: 'Unpublish',
    status: {
      published: 'Published',
      unpublished: 'Unpublished',
    },
  },
  jobsCount: 'Jobs',
  apply: 'Apply',
  applied: 'Applied',
  applyMsg: 'Applied Successfully',
  appliedMsg: 'You have already applied to this job',
  profileSubmited: 'Your profile has been submitted for review',
  jobNoLongerAvailable: 'Job no longer available',
  yourDraftScore: 'Your Draft Score',
  yourDraftScoreSubText: 'You are scored out of 100 based on how well your resume and preferences fit with this job.',
  publishUnpublishMsg: {
    publishMsg: 'Job Opened Successfully',
    unPublishMsg: 'Job Closed Successfully',
    deleteMsg: 'Job Deleted Successfully',
  },
  createJob: 'Create job',
  createJobSteps: {
    jobAddedSuccessFully: 'Job added successfully',
    role: {
      title: 'Role',
      jobRoleRequired: 'Job title is required',
      maxWord: 'maximum words allowed',
      heading: 'What type of role are you hiring?',
      subHeading:
        'Use the appropriate title and role to make sure the job is being seen by the right candidates.',
      specifyText:
        'Please specify the job title as single job position like ',
      projectManager: '"Product Manager" ',
      orTxt: 'or ',
      reactDeveloperTxt: '"React JS Developer"',
      specifyTextTwo: ', not a sentence like "Looking for PM / Dev / Engineering Manager".',
      specifyTextThree:
        ' If you need to post multiple roles, please create a separate job for each one.',
      placeholder: 'Enter Job Title',
      label: 'Job Title',
      roleType: {
        label: 'Functional role',
        placeholder: 'Functional role',
      },
      findRoleTxt: 'Can’t find your role?',
      nextBtnTxt: 'Next',
      cantFindRole: {
        title: 'Can’t find your role?',
        desc: "If you can't find a suitable category, then we don't currently support those roles. Let us know so we can consider adding that role.",
        contactUsAt: 'Contact us at:',
        draftUrl: 'support@thedraft.io',
        close: 'Close',
      },
    },
    details: {
      title: 'Details',
      doneBtnTxt: 'Done',
      detailsHeading: 'Build your smart job profile',
      subHeadingTxtOne:
        "These details will be shown to candidates and will help determine if they're suitable, saving both sides time. Keep this in mind as being precise here will help you get more relevant applications.",
      subHeadingTxtTwo:
        'You will be able to edit these details before opening the job.',
      skillCardHeading: 'Skills you have',
      skillCardTypographyTxtOne:
        'Tag any skills and technologies that are key for this role. Only tag those that are relevant to help ensure the best suited candidates are seeing this job.',
      skillCardTYpographyTxtTwo:
        'This works well when you include the top 5-10 skills and technologies.',
      addSkillButtonTxt: 'Add skills and technologies',
      requirementCardHeading: 'Who you are',
      requirementCardTypographyTxtOne:
        'Share the kind of candidate you are looking for and what is required to get hired for this job.',
      requirementCardTypographyTxtTwo:
        "Whether your culture is serious or laid back, your candidates viewing your job are people. So write as if you're speaking to them.",
      addRequirementButtonTxt: 'Add requirements',
      responsibilityCardHeading: 'What you will do',
      responsibilityCardTypographyTxtOne:
        'Explain what the job role involves day to day.',
      responsibilityCardTypographyTxtTwo:
        'Candidates are looking for a clear understanding of their core responsibilities and what you will expect of them.',
      addResponsibilityBtnTxt: 'Add responsibilities',
      skillPopup: {
        addSkill: 'Add skill',
        skillPopupHeading: 'Skills you have',
        skillPopupSubHeading: 'Skills and technologies',
        skillPopupContentOne: 'Only add skills and technologies that are relevant to help ensure the best suited candidates are seeing this job. Consider the relative importance of each to get better matches.',
        skillPopupContentTwo: 'Candidates will not be shown the exact priorities so avoid the urge to mark all as non-negotiable as this will impact the size of the talent pool recommended. ',
        skillPopupContentThree: 'This works well when you include at least the top 5 skills and technologies.',
        skillSliderTitels: ['Desired', 'Preferable', 'Non-negotiable'],
        newSkillOptionsPlaceholder: 'Type new skill or technology here',
        inputPlaceholder: 'Type new skill or technology here',
        error: "You've reached the 10 skills maximum that can be added to this job.",
        cancel: 'Cancel',
        save: 'Save',
      },
      whoYouArePopup: {
        heading: 'Who you are',
        content: 'Share the kind of candidate you are looking for and what is required to get hired for this job.',
        subText: 'Share the kind of candidate you are looking for and what is required to get hired for this job. Whether your culture is serious or laid back, your candidates viewing your job are people. So write as if you\'re speaking to them.',
        inputPlaceholder: 'Select an option',
        employmentTypeLabel: 'Employment type',
        basicSalary: 'Base salary',
        basicSalaryContent: "We'll only show this job to candidates if it meets their minimum salary expectations.",
        targetEarningHeading: 'Total on-target earnings (OTE) (Optional)',
        targetEarningContent: 'This figure should include the base salary and any bonuses to provide an accurate picture of total compensation.',
        langContainerHeading: 'Language requirements  (Optional)',
        langContent: "Only add a language if it's a must have for this job. A candidate won't be shown this job if they are not comfortable working in at least one of the required languages.",
        addMoreHeading: 'Add more',
        addMoreContent: "Whether your culture is serious or laid back, your candidates viewing your job are people. So write as if you're speaking to them.",
        card: {
          ote: 'Total on-target earnings (OTE)',
          language: 'Language requirements',
        },
        languageSubText: 'Jobs on The Draft require English. Add other required languages here and we\'ll recommend  your job to relevant candidates.',
      },
      whatWillYouDoPopup: {
        title: 'What you will do',
        subText: 'Explain what the job role involves day to day and the core responsibilities. Share any points that will give candidates a clear understanding of their responsibilities and what you will expect of them.',
        subtitle: 'Explain what the job role involves day to day and the core responsibilities.',
        roleType: {
          label: 'Role type',
          placeholder: 'Select an option',
        },
        range: {
          label: 'How many people will report to this role?',
          subLabel: 'Include direct reports and their teams',
          placeholder: 'Select a range',
          cardLabel: 'Total people managed',
        },
        workStyle: {
          label: 'Work style',
          placeholder: 'Select work style',
          remote: 'Remote',
        },
        location: {
          label: 'Where is this role based?',
          blockLabel: 'Location',
          placeholder: 'Type a city',
        },
        regions: {
          label: 'What location is this remote job restricted to?',
          subLabel: 'If this remote job is not restricted to a specific location or timezone, please select "Worldwide" so you have access to a global pool of talent.',
          placeholder: 'Type a location like Worldwide, Europe, or US',
        },
        officeDaysPerWeekType: {
          label: 'Days per week in office',
          subLabel: 'How often is the candidate expected to come into the office each week? Leave the maximum blank if you only have a minimum number of office days.',
          placeholder: 'Set office days per week',
        },
        minimumDays: {
          label: '',
          placeholder: 'Minimum days',
        },
        maximumDays: {
          label: '',
          placeholder: 'Maximum days',
          blockPostFix: ' days',
          blockMiddleText: ' to ',
        },
        addMore: {
          label: 'Add more',
          subLabel: 'Share any additional points that will give candidates a clear understanding of their responsibilities and what you will expect of them.',
          placeholder: 'Work closely with the product and designs teams to solve exciting and challenging problems for our users',
          buttonText: 'Add responsibility',
        },
      },
    },
    brand: {
      title: 'Brand',
    },
  },
  editJobSteps: {
    editHeading: 'Edit snapshot',
    editSubText: 'These details will be shown to candidates and will help determine if they\'re suitable, saving both sides time.',
    optional: '(optional)',
    experienceHeading: 'Experience',
    roleTypeSubText: 'Let candidates know whether this role has any management responsibilities',
    languageHeading: 'Language',
    languageField: 'Language requirements (Optional)',
    roleHeading: 'Role',
    jobTitle: 'Job Title',
    jobTitleSubText: `Please specify the job title as a single job position like "Product Manager" or "React JS Developer", 
    not a sentence like "Looking for PM / Dev / Engineering Manager". 
    If you need to post multiple roles, please create a separate job for each one.`,
    roleSubText: 'Use the appropriate title and role to make sure the job is being seen by the right candidates.',
  },
  skillsBlock: {
    skillsYouHave: 'Skills you have',
    onYourResume: 'On your resume',
    missingFromYourResume: 'Missing from your resume',
    noMatchingSkills: 'No matching skills based on your profile',
  },
  officeDaysPerWeeks: {
    occasionally: 'Occasionally',
    setOfficeDaysPerWeek: 'Set office days per week',
  },
  regionsOptions: {
    regions: {
      title: 'Regions',
      amaricas: 'Americas (NA + LATAM)',
      apac: 'Asia-Pacific (APAC)',
      eur: 'Europe',
      emea: 'Europe, the Middle East and Africa (EMEA)',
      latam: 'Latin America (LATAM)',
      na: 'North America (NA)',
      worldwide: 'Worldwide',
    },
    countries: {
      title: 'Countries',
      AUT: 'Austria (AUT)',
      AUS: 'Australia (AUS)',
      CAN: 'Canada (CAN)',
      BEL: 'Belgium (BEL)',
      DNK: 'Denmark (DNK)',
      FRA: 'France (FRA)',
      DEU: 'Germany (DEU)',
      HKG: 'Hong Kong (HKG)',
      IRL: 'Ireland (IRL)',
      IND: 'India (IND)',
      JPN: 'Japan (JPN)',
      MYS: 'Malaysia (MYS)',
      NLD: 'Netherlands (NLD)',
      NZL: 'New Zealand (NZL)',
      PRT: 'Portugal (PRT)',
      SGP: 'Singapore (SGP)',
      ESP: 'Spain (ESP)',
      CHE: 'Switzerland (CHE)',
      UAE: 'United Arab Emirates (UAE)',
      US: 'United States (US)',
      UK: 'United Kingdom (UK)',
    },
  },
  closeJobModal: {
    heading: 'Close Job',
    subHeading: 'Are you sure you want to close this job?',
    desc1: 'Closing this job will remove it from the feed and stop accepting applications.',
    desc2: 'You can always re-open a job from your archived jobs.',
    yesOption: 'Yes',
    noOption: 'No',
    hiredForThisRoleTitle: 'Did you hire for this role?',
    foundCandidateOnDraftTitle: 'Great! Did you find candidate on The Draft?',
    candidateName: {
      label: 'Candidates name',
      placeholder: 'Candidates name',
    },
    cancel: 'Cancel',
    closeJob: 'Close job',
  },
  jobHeader: {
    edit: 'Edit Job',
    applicants: 'Applicants',
    messages: 'Messages',
    sourcing: 'Recommendations',
  },
  applicants: {
    noApplicants: {
      title: 'No Applicants Yet',
      discription: 'All applicants who applied will be listed here. Review the talent pool to find your superstar candidate!',
      startSourcing: 'Start Sourcing',
    },
    noRecmmendation: {
      title: 'No candidates match',
      discription: 'Your current criteria may be too strict. Try adjusting the importance of the skills and technologies required.',
      startSourcing: 'Apply filters',
    },
    noMessages: {
      title: 'No messages to display',
      discription: 'Messages to any prospects or applicants for this job will appear here.',
    },
    filters: 'Filters',
    search: 'Search applicant name',
    shortlisted: 'Shortlisted',
    skills: 'SKILLS',
    draftScore: 'Draft Score',
    message: 'Message',
    applied: 'Applied',
    draftScoreSubText: 'Candidates are scored out of 100 based on how well their resume and preferences fit with your job',
  },
  status: {
    open: 'open',
  },
};

const cronycleFeed = {
  loginLink: 'Login',
  accessCronycle: 'Access Cronycle',
  linkAccountText: 'Link with your Cronycle account',
  refreshButtonText: 'Refresh feed list',
  connectButtonText: 'Connect',
  title: 'Cronycle feeds',
  feedCompany: 'The Draft',
  labels: {
    status: 'Status:',
    contentType: 'Cronycle content type:',
    fetchDate: 'Cronycle fetch date:',
  },
  visible: 'Visible',
  hidden: 'Hidden',
};

const feed = {
  noResultFor: 'No results for',
  noResultMessage: 'We didn’t find anything matching the criteria',
  noFeedFound: 'Feeds not found!',
  filters: {
    users: { key: 'users', label: 'PEOPLE' },
    articles: { key: 'articles', label: 'ARTICLES' },
    jobs: { key: 'jobs', label: 'JOBS' },
    companies: { key: 'companies', label: 'COMPANIES' },
    posts: { key: 'posts', label: 'POSTS' },
    links: { key: 'links', label: 'LINKS' },
  },
  moreLikeThis: 'More Like This',
};

const article = {
  chooseType: 'Choose your card type ',
  title: 'Article',
  articleDescription: 'Long-form content to share valuable information.',
  post: 'Post',
  postDescription: 'Best for quick updates. Cards only',
  creatingArticle: 'Write a story',
  step: {
    create: 'Create Card',
    tags: 'Tags',
  },
  editText: {
    placeholder: 'Write your article...',
    placeholderTitle: 'Add title...',
    storyPreview: 'Story Preview',
  },
  tags: {
    title: 'Tag topics',
    subtitle: 'Tag related topics to reach people interested in content like this.',
    label: 'Topics',
    placeholder: 'Search tags...',
  },
  next: 'Next',
  preview: 'Preview',
  cancel: 'Cancel',
  discard: 'Discard',
  back: 'Back',
  publishArticle: 'Publish',
  unpublishArticle: 'Unpublish',
  status: 'Status',
  unpublishDate: 'Not Published',
  moreMenu: {
    edit: 'Edit',
    viewDetails: 'View',
    unpublish: 'Unpublish',
    publish: 'Publish',
    status: {
      published: 'Published',
      unpublished: 'Unpublished',
    },
  },
  followButtonLabel: 'Follow',
  articleSavedSuccess: 'Article Saved Successfully',
  articleRemovedSuccess: 'Article Removed Successfully',
  companySavedSuccess: 'Company Saved Successfully',
  companyRemovedSuccess: 'Company Removed Successfully',
  companySaveError: 'Error in saving company',
  articleSaveError: 'Error in saving article',
  jobsSavedSuccess: 'Job Saved Successfully',
  jobsRemovedSuccess: 'Job Removed Successfully',
  jobsSaveError: 'Error in saving job',
  userSavedSuccess: 'User profile Saved Successfully',
  userRemovedSuccess: 'User profile Removed Successfully',
  userSaveError: 'Error in saving user profile',
  postSavedSuccess: 'Post Saved Successfully',
  postRemovedSuccess: 'Post Removed Successfully',
  postSaveError: 'Error in saving post',
  linkSavedSuccess: 'Link Saved Successfully',
  linkRemovedSuccess: 'Link Removed Successfully',
  linkSaveError: 'Error in saving link',
  imageUpload: {
    logoInputInfo: 'Drag and drop file or Browse',
    imageInputLabel: 'Add story image preview ',
    imageInputLabelMobile: 'Add story preview ',
    file: 'PNG or JPEG',
    fileSize: 'Less than 20MB',
  },
  discardModal: {
    title: 'Discard this article?',
    description: 'Your story won\'t be saved.',
    cancelButton: 'Continue writing',
    saveForLater: 'Save for later',
    submitButton: 'Discard',
  },
  input: {
    caption: {
      title: 'Add description',
      subtext: 'Summarise what your article is about. Include #hashtags to help readers find this content.',
      placeholder: 'Add description',
    },
    topics: {
      title: 'Tag topics',
      subtext: 'Tag related topics to reach people interested in content like this.',
      placeholder: 'Search tags',
    },
  },
  deleteModal: {
    title: 'Delete this story?',
    subtitle: 'This article will be removed for everyone.',
    cancelButton: 'No, keep article',
    deleteButton: 'Yes, delete',
    successMessage: 'Deleted story successfully',
  },
};

const cards = {
  noCards: 'No Cards',
  noCardDesc: 'You haven’t created any cards yet.',
  createCards: 'Create Cards',
  cards: 'Cards',
  aboutCardDescription: 'Describe yourself, your brand or a piece of content.',
  linkCardDescription: 'Share key links designed to tell your community what to do or where to go.',
  editCards: 'Edit Cards',
  coverCard: 'Cover Card',
  card: 'Card',
  saveCard: 'Save Card',
  deleteCards: 'Delete Card',
  deleteLink: 'DELETE LINK',
  meta: {
    user: 'Capture the attention of hiring managers with a clear cover card. This will be the first card in your brand stack that appears on the feed.',
    article: 'Capture the attention of readers with an inviting cover card.',
    job: 'Jobs can often be the first contact candidates have with your organisation. Your cover card is a perfect way to amplify your employer brand and make it stand out.',
    company: "Use a high-quality photo or video to capture the essence of your organisation's branding.",
  },
  coverCardDescription: { job: 'Edit the details on the job profile if you want to amend the key job highlights shown on the cover card. ' },
};
const discardModal = {
  discardChanges: 'Discard changes?',
  description: 'Going back will delete changes to your cards.',
  cancelButton: 'No, keep editing',
  submitButton: 'Yes, discard changes',
};
const deleteModal = {
  title: 'Are you sure?',
  description: 'Are you sure you want to delete this card?',
  cancelButton: 'No, keep card',
  submitButton: 'Yes, delete card',
};
const savedCards = {
  noCards: 'No saved cards',
  noCardDesc: 'Save some cards first',
  createCards: 'Go to Feed',
  savedCards: 'Saved Cards',
};

const comments = {
  title: 'Comments',
  placeholder: 'What are your thoughts?',
  noComment: 'There are currently no comments for this content. Be the one to start the discussion.',
  noCommentYet: 'No comments yet.',
  startConversation: 'Start the conversation.',
  addComment: 'Add Comment',
  published: 'Published',
  post: 'Post',
};
const cardCreationWizard = {
  addCard: 'Add Card',
  coverCardText: {
    mantraLabel: 'Mantra*',
    mantraPlaceholder: 'This could be your favourite quote, a positive phrase, a proverb or an affirmation – anything that resonates with you.',
    mantraPlaceholderForContent: 'Add text',
  },
  aboutCardText: {
    aboutLabel: 'Description*',
    aboutPlaceholder: 'Add text',
    headingLabel: 'Heading',
    headingPlaceholder: 'What is this card about?',
  },
  AddMedia: 'Add media',
  addContent: 'Add Content',
  chooseCardType: 'Choose card type',
  image: {
    imageInputInfo: 'We support PNG, JPG, MP4 and MOV files.',
    contentImageInputInfo: 'Max file size: YY mb, format: png, jpg, mp4 At least 290x500px',
    logoInputInfo: 'We support PNG and JPG files.',
    error: 'File format not supported',
  },
  linkCard: {
    linkText: 'Link',
    linkFieldTitleLabel: 'Name',
    linkFieldTitlePlaceholder: 'Name your link',
    linkFieldUrlPlaceholder: 'https://www.example.com',
    addAnotherLink: 'Add another link',
    linkFieldUrlLabel: 'URL',
  },
  coverCardSubtext: 'Capture the attention of readers with a clear cover card.',
  addMedia: 'Add Media',
  addLogo: 'Add Logo',
  imageError: 'Selected file is to big or unsupported format',
  previewStep: {
    title: 'Preview',
    subtitle: 'This is a preview of your card.',
  },
};
const notifications = {
  title: 'Notifications',
  noNotification: 'No notifications',
  noNotificationDesc: 'You have no notifications yet.',
  noNotificationDesc2: 'When you have notifications, they will appear here.',
  noNotificationDesc3: 'You can also check your email for notifications.',
  commentsNotification: 'commented on your article',
  upvoteNotification: 'upvoted your article',
  allNotifications: 'All Notifications',
};
const followUsers = {
  follow: 'Follow',
  unFollow: 'Unfollow',
};
const deck = {
  saveDeck: 'Save Deck',
  editDeck: 'Edit Deck',
};
const createContent = {
  create: 'Create',
  post: 'Post',
  article: 'Article',
  postDescription: 'Share images and videos to get your message out there and grow your audience.',
  articleDescription: 'Grow your community with your writing by sharing in-depth thoughts around topics you are passionate about.',
  job: 'Job',
  jobDescription: 'Create a new job and find your next hire.',
  link: 'Share link',
  linkDescription: 'Share a link to a story or anything you find interesting.',
};
const posts = {
  pageTitle: 'Creating Post',
  createPosts: 'Create Posts',
  createPost: 'Create Post',
  noPostDesc: 'You haven’t created any posts yet.',
  noPosts: 'No Posts',
  uploadMedia: {
    title: 'Upload media',
    tag: 'Tag related topics to reach people interested in content like this.',
    subText: ["People won't see your tagged topics.", 'Please tag at least 1 topic.'],
  },
  changeMedia: 'Change Media',
  input: {
    caption: {
      title: 'Add caption',
      placeholder: 'Write a caption',
      subtext: 'A relevant caption will help your post show up for the correct searches and related content.',
    },
    topics: {
      title: 'Tag topics',
      placeholder: 'Search tags',
      subtext: "Tag related topics to reach people interested in content like this. These topics won't be visible to anyone other than you.",
    },
  },
  steps: {
    addMedia: 'Add media',
    tags: 'Tags',
  },
  discardModal: {
    title: 'Discard this post?',
    subtitle: 'All edits won’t be saved.',
  },
  options: 'Options',
  successMessage: 'Post added successfully!',
  reorder: 'Click and drag to reorder',
  crop: 'Crop',
  remove: 'Remove',
  reorderLabel: 'Reorder',
  delete: 'Delete',
  deleteModal: {
    title: 'Delete this post?',
    subtitle: 'This post will be removed for everyone.',
    cancelButton: 'No, keep',
    deleteButton: 'Yes, delete',
  },
};

const userOnBoarding = {
  title: 'Set up your profile',
  step: {
    name: 'Name',
    resume: 'Resume',
    brand: 'Brand',
  },
  label: {
    WelcomeLabel: 'Welcome!',
    FirstConfirmYourName: 'First, confirm your name',
    stepTwoHeading: 'Now let’s start building your digital resume',
    workExperience: 'Experience',
    education: 'Education',
    notStarted: 'Not Started',
  },
  content: {
    welcomeContent: "Let's get you started in a few steps that will help explain the basics of how you can create and customise your professional profile.",
  },
  profileForm: {
    profileText: {
      paragraphOne: 'Your name will be used for creating your unique profile link that you can share with everyone',
      paragraphTwo: 'Your profile link affects the way people see the professional you and plays a significant role in how well your profile ranks on The Draft and on search engines.',
    },
    FirstnameInput: {
      firstname: 'First name',
      placeholder: 'Your first name',
      error: 'First name is required.',
    },
    LastnameInput: {
      Lastname: 'Last name',
      placeholder: 'Your last name',
      error: 'Last name is required.',
      maxCharactersRefired: 'Maximum 100 characters allowed',
      minCharactersRefired: 'Minimum 3 characters required',
    },
    location: {
      placeholder: 'Enter location',
      label: 'Where are you based?',
    },
  },
  onBoardingResumeTab: {
    title: 'Now let’s start building your resume',
    subTitleOne: 'Experience',
    subTitleTwo: 'Education',
    resumeText: {
      resumeTextOne: 'This will be visible on your profile. The more you add the better chances you have of being discovered and hired for your ideal role.',
      resumeTextTwo: 'Add at least your current role or your highest level of formal education if you’e a recent graduate looking for your first role.',
    },
  },
  stepTwoContent: {
    paragraphOne: 'This will be visible on your profile. The more you add the better chances you have of being discovered and hired for your ideal role.',
    paragraphTwo: 'Add at least your current role or your highest level of formal education if you’e a recent graduate looking for your first role.',
  },
  resume: {
    title: 'What is your current role?',
    workExperience: 'Work experience',
    sideProjects: 'Side projects',
    add: {
      description: 'Add where you have worked and describe each work experience',
      addWorkExperience: 'Add work experience',
      addYourEducation: 'Add your education',
      addEducation: 'Add education',
      addEducationText: 'Add your highest level of formal education and any relevant professional qualifications',
    },
    deleteSuccess: 'Experience deleted successfully.',
    deleteEducationSuccess: 'Education deleted successfully.',
  },
  brand: {
    createMessage: 'Create your brand stack',
    subtitle1: 'Introduce who you are to the world using a collection of cards.',
    subtitle2: 'Your cards will be used to represent you on the feed to hiring companies and other users so make your first impression count!',
    subtitle2Organization: 'Your cards will be used to represent you on the feed to talented candidates so make your first impression count!',
  },
  successModal: {
    title: 'Looks great!',
    subtitle: 'Tap the back arrow on your profile to go to the feed.',
    desc: "You can continue customising your page to make it personal to you and show everyone what you're all about.",
    button: {
      cancel: 'Go to Feed',
      submit: 'Go to profile',
    },
  },
};

const messages = {
  noMessagesToDisplay: 'No messages to display',
  noJobMessagesToDisplay: 'No job messages yet',
  reasonTitle: 'Organisations can message you for two reasons:',
  reason1: '1. To reply to your job application',
  reason2: '2. When your profile matches the job they are hiring for.',
  startFollowingToMessage: 'Start following people to message them',
  messages: 'Messages',
  message: 'Message',
  followers: 'Followers',
  jobs: 'Jobs',
  beginningOfConversation: 'This is the beginning of your conversation',
  sendFirstMessage: 'Send first message',
  writeMessage: 'Write a message....',
  deleteMessage: 'Delete',
  begningOfJobConversation: 'Beginning of the conversation',
  begningOfJobConversationSub: 'You see this because someone found your profile....',
};
const actionBar = {
  copyLink: 'Copy link',
};

const preferences = {
  job: {
    title: 'Job Preferences',
    successfulMessage: 'Job Preferences set successfully',
    joiningPreference: {
      title: 'When are you looking to start a new job?',
      subtitle: 'Let us know where you are in your job search.',
      placeholder: 'Select preference',
    },
    salary: {
      title: 'What is your minimum expected salary?',
      subtitle: "We won't recommend jobs that are below your base salary expectation.",
      label: 'Salary (yearly, pre tax)',
      placeholder: '$40,000',
    },
    compensation: {
      title: 'What is your desired total annual compensation (Including base salary and any bonuses) ?',
      subtitle: "If you set your total compensation then you won't be recommended jobs that do not meet this expectation.",
      label: 'Salary (Total annual compensation, pre tax)',
      placeholder: '$40,000',
    },
    language: {
      title: 'Which languages can you work in?',
      subtitle: 'Add any languages that you are comfortable working in so we can show you relevant jobs.',
      placeholder: 'Type a language here',
    },
    employmentType: {
      title: 'What type of employment positions are you interested in?',
      subtitle: 'Select all the types you would be open to.',
    },
    location: {
      title: 'Where would you like to work?',
      subtitle: 'Select up to 5 locations',
      placeholder: 'Type a city',
    },
    region: {
      title: 'Where could you work remotely from?',
      subtitle: 'Which location and timezone restrictions would you be able to meet for a remote job. Select up to 5 options.',
      placeholder: 'Type a location like Worldwide, Europe, or US',
    },
    role: {
      title: 'Type of roles',
      subtitle: 'What types of roles would you like to see? Select the most relevant for you (max 5).',
      placeholder: 'Type a role name',
    },
    workStyle: {
      title: 'What work style(s) are you willing to consider?',
      hybridLabel: 'Hybrid',
      subtitle: 'Choose how you want to work.',
      officeDaysPerWeek: {
        label: 'How often are you willing to come into the office each week?',
        placeholder: 'Set office days per week',
      },
      range: {
        label: 'Leave the maximum blank if you only have an expectation for minimum number of office days.',
        minimumDaysPlaceholder: 'Minimum days',
        maximumDaysPlaceholder: 'Maximum days',
      },
    },
    industries: {
      title: 'Favourite industries',
      subtitle: 'All organisations are classified according to its principal business activity using the Global Industry Classification Standard (GICS®). This hierarchical industry classification system offers four levels of analysis, ranging from the most general sector to the most specialized sub-industry. The GICS structure consists of 11 Sectors, 25 Industry groups, 74 Industries and 163 sub-industries.',
      selector: {
        subtext: 'Narrow your search by choosing from the list of sectors below. ',
      },
      subIndustries: {
        description: 'Which sub-industries are you most interested in? (Select as many as you like)',
      },
    },
  },
};
const SEO = {
  insightsPage: {
    title: 'Insights | The Draft',
    description: 'Learn about %companyName%\'s company activity, investors, funding and competitors.',
  },
  jobsPage: {
    title: '[0] at [1] in [2] | The Draft',
    description: 'Explore the [0] job role at [1] in [2]. Find the right job at [3] by signing up to The Draft.',
  },
  articlePage: {
    title: '[0] | The Draft',
    description: 'Read about [0] by [1] to learn more.',
  },
  userContentPage: {
    title: '[0] Content | The Draft',
    description: 'Learn about [0]s content to explore their ideas and thoughts on key topics.',
  },
  userResumePage: {
    title: '[0] Resume | The Draft',
    description: 'Learn about [0]\'s resume to explore their work experience, education and skill set.',
  },
};
const linkPosts = {
  creatingLinkPost: 'Share link',
  shareALink: 'Share a link',
  description: 'Share a link to a story or anything you find interesting from all your favourites sources:',
  placeholder: 'Enter or paste a link',
  errorMessage: 'Unsupported link type',
  linkPreview: 'Link Preview',
  addLinkTitle: 'Add link title',
  linkCreatedSuccess: 'Link created successfully',
  input: {
    caption: {
      title: 'Add description',
      placeholder: 'Add description',
      subtext: 'Share some additional details and include #hashtags to help readers find your link.',
    },
  },
  discardModal: {
    title: 'Discard this link?',
    subtitle: 'your link won’t be saved.',
  },
};
const githubCard = {
  title: 'My Github',
  daysOfCoding: 'Days of coding',
  totalContributions: 'Total contributions',
  mostContributions: 'Most contributions',
  discoverText: 'Discover',
};

const userBio = {
  followersTxt: 'followers',
  followingTxt: 'following',
  followedBy: 'Followed by',
  more: 'more',
  hide: 'Hide',
  bioBtn: 'Bio',
  addBioText: 'Summarise who you are to be found on the explore page.',
  editBioBtnText: 'Edit Bio',
};

const EditProfileBioModal = {
  bio: 'Bio',
  addProfileImageText: 'Add profile image',
  firstNameLabel: 'First Name',
  firstNamePlaceholder: 'What\'s your first name?',
  lastNameLabel: 'Last Name',
  lastNamePlaceholder: 'What\'s your last name?',
  locationLabel: 'Location',
  locationPlaceholder: 'Where are you currently based?',
  mantraLabel: 'Mantra',
  mantraPlaceholder: 'This could be your favourite quote, a positive affirmation or the type of job role you do – anything that resonates with you.',
  cancelBtn: 'Cancel',
  saveBtn: 'Save',
  imageInputLabel: 'Add profile image ',
  imageInputLabelMobile: 'Add story preview ',
  fileExtension: 'PNG or JPEG',
  fileSize: 'Less than 5MB',
  profileImageSizeError: 'Profile image should be less than 5 MB',

};

const ImageCropModal = {
  cropModalHeading: ' Crop profile image',
};

const homePage = {
  banner: 'There\'s no more workplace you.',
  bannerTextDescription: 'Highlight more than just your accomplishments at work — Discover premium opportunities, master new skills, and perfect your niche with a smarter way to network.',
  startForFree: 'Start for Free',
  banner2: 'It\'s just',
  banner3: 'you.',
  header: {
    menu: 'Menu',
  },
  youSection: {
    title: 'It\'s time you showed up to work as, well... you.',
    subTitle: 'Break free of stereotypes. Labels should be chosen, not given. Craft a narrative that authentically represents who you are, what you create, and what you bring to the table.',
    subTitle2: 'Express your individual truth through your personal profile and show every unique side of you.',
    createMyProfile: 'Create my profile',
    myInstagram: 'My Github',
    letsConnect: 'Let\'s connect',
    bioTitle: 'Bio',
    bio: 'I partner with non-technical founders to build and grow innovative startups by day and I\'m a budding online entrepreneur by night.',
  },
  careerSection: {
    title: 'The life you’re building, with a career you love.',
    feature1Title: 'Real Transparency',
    feature1SubTitle: 'Better understand potential employers, their values, and decide for yourself what aligns ',
    feature1CTA: 'Search opportunities',
    feature2Title: 'Target with Precision',
    feature2SubTitle: 'Optimize your resume, highlight your wins, and say something meaningful. The Draft’s suite of tools empower candidates to put their best foot forward.',
    feature3Title: 'Insights that Inspire',
    feature3SubTitle: 'The Draft offers meaningful insights that enable you to make smart choices',
    feature4Title: 'Dylan Jadeja',
    feature4SubTitle: 'Chief executive officer',
    feature5Title: 'Our values',
    feature5SubTitle: '',
    feature6Title: 'From our CEO',
    feature6SubTitle: '',
  },
  connectSection: {
    title1: 'Level',
    title2: 'the playing field',
    subTitle: 'Better understand your network. Connect authentically.Build something together.',
    makeConnections: 'Make connections',
    applyForJobs: 'Apply for jobs',
    productManager: 'Product Manager',
    block11Text: 'I love this! Great to get a peek into how you manage your hiring process. Already have some ideas we can try out. Thanks for sharing.',
    ann: 'Ann',
    block12Title: 'Hiring Process for a Product Manager',
  },
  exploreSection: {
    title: 'Explore the stories worth sharing.',
    subTitle: 'Access the information that matters most From news, to blogs, and original content, The Draft optimizes content that helps you grow.',
    exploreNow: 'Explore Now',
  },
  exploreSection2: {
    title: 'There\'s room for everyone.',
    subTitle: 'Explore yourself. The Draft is more than just a job board or social network. It\'s a professional ecosystem that enables people to better represent themselves and their dynamic interests.',
  },
  roomForEveryone: {
    forTalent: {
      title: 'For Talent',
      feature1: 'Create content',
      feature2: 'Build audience',
      feature3: 'Share your story',
      feature4: 'Find inspiration',
      cta: 'Sign Up',
    },
    forBusiness: {
      title: 'For Businesses',
      feature1: 'Create content',
      feature2: 'Find talent',
      feature3: 'Show your values',
      feature4: 'Post jobs',
      cta: 'Read More',
    },
  },
  footer: {
    signUpNow: 'Sign up now',
    moreInfo: 'More Info',
    privacyPolicy: 'Privacy Policy',
    contactUs: 'Contact Us',
    termsOfUse: 'Terms of Use',
    forMoreInfo: 'For more info',
  },
};
const businessPage = {
  heroBanner: {
    banner: 'Your destination for hiring best-in-class talent, that shares your values.',
    bannerTextDescription: 'Reimagining job discovery and matching',
    getStarted: 'Get Started',
    forBusiness: 'For business',
    featureTitle: 'Amplify your employer brand',
    detail1: 'Make your employer brand stand out to top candidates like never before. Highlight your mission, values, benefits and more to give top candidates a true picture of what makes you great.',
    detail2: 'Retain brand consistency across your hiring touchpoints — right from when they first discover or engage with your brand through looking at your job ad.',
  },
  draftVsOther: {
    title: 'The Draft vs. the others',
    featureText: {
      feature1: 'Seamless integration with your ATS of choice',
      feature2: 'Best-in-class talent in one central destination',
      feature3: 'Holistic view of the talent marketplace',
      feature4: 'Proprietary matching system that removes human bias and reduces noise in hiring pipelines',
      feature5: 'Credible validation of individuals\' skills, experience, and fit',
      feature6: 'Better matching to roles/search criteria',
      feature7: 'Greater insight on individuals and candidates',
      feature8: 'Community building',
      feature9: 'Value and mission showcase through rich, digital media',
      feature10: 'More efficient candidate search and shortlisting',
      feature11: 'Reduced costs per hire',
    },
    ctaTitle: 'Register your business',
    ctaTitle2: 'and learn more about The Draft',
    ctaButtonText: 'Register today',
  },
  source: {
    title: 'Source smarter, not harder',
    desc1: 'Job discovery has become a digital journey that extends beyond the traditional job-search sites and behaviors.',
    desc2: 'With us you can reach and engage future potential hires through dynamic, visually engaging posts, articles and links to anything that resonates with your employer brand.',
    desc3: 'Share your successes but also your challenges, work culture, and values to provide a more holistic and honest view of your identity.',
  },
  lead: {
    title: 'Don’t lose your lead',
    desc1: 'Job discovery has become a digital journey that extends beyond the traditional job-search sites and behaviors.',
    desc2: 'With us you can reach and engage future potential hires through dynamic, visually engaging posts, articles and links to anything that resonates with your employer brand.',
    desc3: 'Share your successes but also your challenges, work culture, and values to provide a more holistic and honest view of your identity.',
  },
  team: {
    title: 'Let your team shine',
    desc1: 'We enable you to showcase the experiences of your real employees to increase authenticity and build trust. Top talent will trust these voices three times more than your organisation itself when trying to understand what it\'s truly like to work there.',
  },
};

const bugSnag = {
  errorText: 'Bugsnag API key is empty. Bugsnag initialization skipped.',
};
const privacyPolicy = {
  title: 'Privacy Policy',
};
const cookieConsentText = {
  consentModal: {
    title: "You're in control",
    description:
      'We use cookies (and other similar technologies) to improve your experience on our site. Click \'Accept\' to agree or click ‘Manage preferences’ to customize.',
    acceptAllBtn: 'Accept',
    acceptNecessaryBtn: 'Reject',
    showPreferencesBtn: 'Manage preferences',
  },
  preferencesModal: {
    title: 'Cookie preferences',
    acceptAllBtn: 'Accept all',
    acceptNecessaryBtn: 'Reject all',
    savePreferencesBtn: 'Save preferences',
    closeIconLabel: 'Close',
    sections: [
      {
        title: 'Cookie Usage',
        description:
          'Cookies help us understand how visitors use our website so we can provide the best possible experience. You can opt-in/out for such tracking. For more details relative to cookies and other sensitive data, please read the full <a href="/privacy-policy" target="_blank" class="cc__link">privacy policy</a>.',
      },
      {
        title: 'Strictly Necessary Cookies',
        description: 'Enables essential services and functionality, including identity verification, service continuity and site security. Opt-Out is not available.',
        linkedCategory: 'necessary',
      },
      {
        title: 'Performance Cookies',
        linkedCategory: 'analytics',
        description: 'Collects anonymous data about how visitors use our site and how it performs. They help us to know which pages are the most and least popular and see how visitors move around the site.',
      },
      {
        title: 'More information',
        description:
          'For any queries in relation to our policy on cookies and your choices, please <a class="cc__link" href="mailto:comms@thedraft.io">comms@thedraft.io</a>.',
      },
    ],
  },
};
export const lang = {
  exampleTopBar,
  exampleSidebar,
  PasswordError,
  SignUp,
  SignIn,
  ResetPassword,
  RecoverPassword,
  onBoarding,
  profile,
  errorMessages,
  bio,
  projects,
  buttonText,
  navBarText,
  company,
  workspace,
  jobs,
  cronycleFeed,
  article,
  cards,
  comments,
  savedCards,
  cardCreationWizard,
  discardModal,
  deleteModal,
  notifications,
  feed,
  image,
  fileSpecificationModal,
  followUsers,
  deck,
  createContent,
  posts,
  organization,
  userOnBoarding,
  meltwater,
  messages,
  orgInsightsTab,
  actionBar,
  preferences,
  SEO,
  linkPosts,
  githubCard,
  userBio,
  homePage,
  EditProfileBioModal,
  ImageCropModal,
  businessPage,
  bugSnag,
  privacyPolicy,
  cookieConsentText,
};

export default lang;
